### ISSUE TITLE
Can't build stripped down S3 flavor of cachepot

### ISSUE THREAD

**Issue by xrl** [paritytech/cachepot#151]
I want a no-frills cachepot for my S3-powered CI environment but it won't build. My environment:

    % rustc --version
    rustc 1.61.0-nightly (52b34550a 2022-03-15)
    % cargo --version
    cargo 1.61.0-nightly (65c826642 2022-03-09)

The error:

    % cargo install cachepot --version 0.1.0-rc.1 --no-default-features --features=s3
    [[[ SNIP ]]]
    error[E0432]: unresolved import `crate::config::WorkerUrl`
      --> /Users/xlange/.cargo/registry/src/github.com-1ecc6299db9ec823/cachepot-0.1.0-rc.1/src/dist/mod.rs:16:5
       |
    16 | use crate::config::WorkerUrl;
       |     ^^^^^^^^^^^^^^^^^^^^^^^^ no `WorkerUrl` in `config`
    
    error[E0412]: cannot find type `WorkerUrl` in module `crate::config`
       --> /Users/xlange/.cargo/registry/src/github.com-1ecc6299db9ec823/cachepot-0.1.0-rc.1/src/compiler/compiler.rs:725:23
        |
    725 |     Ok(crate::config::WorkerUrl),
        |                       ^^^^^^^^^ not found in `crate::config`
    
    Some errors have detailed explanations: E0412, E0432.
    For more information about an error, try `rustc --explain E0412`.
    error: could not compile `cachepot` due to 2 previous errors
    warning: build failed, waiting for other jobs to finish...
    error: failed to compile `cachepot v0.1.0-rc.1`, intermediate artifacts can be found at `/var/folders/mc/3pj1vp8s239fn610rbv56f440000gp/T/cargo-installTYYXXo`
    
    Caused by:
      build failed

**Comment by drahnr** [comment]
Hey @xrl, thanks for reporting. This is definitely a bug, possible introduced with #134
